stages:
  - build
  - send_likes

check_connection:
  stage: build
  tags:
    - sh-runner
  script:
    - docker build -t leo_liker .
  when: manual

send_likes:
  stage: send_likes
  tags:
    - sh-runner
  script:
    - docker run -e LIKE_COUNT=$LIKE_COUNT -e API_ID=$API_ID -e API_HASH=$API_HASH leo_liker
  when: manual
